/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import Modelo.Calificacion;
import negocio.CalificacionNegocio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import Modelo.Matricula;
import negocio.MatriculaNegocio;
import presentacion.CursoPanel;

/**
 *
 * @author yarie
 */
public class CalificacionesPanel extends javax.swing.JPanel {
    
    private CalificacionNegocio negocio;
    private MatriculaNegocio matriculaNegocio;
    /**
     * Creates new form CalificacionesPanel
     */
    public CalificacionesPanel() {
        
        initComponents();
        
        negocio = new CalificacionNegocio();
        
        matriculaNegocio = new MatriculaNegocio();
    
        cargarTabla();
        cargarCombos();
    }
    
    private void cargarTabla() {

        DefaultTableModel modelo =
                (DefaultTableModel) jTableCalificaciones.getModel();

        modelo.setRowCount(0);
        
        List<Calificacion> lista =
            negocio.obtenerTodas();

        for (Calificacion c : lista) {

            String estado;

            if (c.getNota() >= 70) {
                estado = "Aprobado";
            } else {
                estado = "Reprobado";
            }

            modelo.addRow(new Object[]{
                c.getNota(),
                estado
            });
        }
    }
    
    private void cargarCombos() {

    jcboEstudiante.removeAllItems();
    jcboCurso.removeAllItems();

    for (Matricula m : matriculaNegocio.listar()) {

        if (m.getEstudiante() != null) {

            jcboEstudiante.addItem(
                m.getEstudiante().getNombre()
            );
        }

        if (m.getCurso() != null) {

            jcboCurso.addItem(
                m.getCurso().getNombre()
            );
        }
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlblEstudiante = new javax.swing.JLabel();
        jlblCurso = new javax.swing.JLabel();
        jlblNota = new javax.swing.JLabel();
        jcboEstudiante = new javax.swing.JComboBox<>();
        jcboCurso = new javax.swing.JComboBox<>();
        jtxtNota = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCalificaciones = new javax.swing.JTable();
        jLabelTituloSecundario = new javax.swing.JLabel();
        jtxtObservacion = new javax.swing.JTextField();
        jlblObservación = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(204, 204, 204));
        setName("Calificaciones"); // NOI18N

        jlblEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        jlblEstudiante.setText("Estudiante:");

        jlblCurso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblCurso.setForeground(new java.awt.Color(0, 0, 0));
        jlblCurso.setText("Curso:");

        jlblNota.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblNota.setForeground(new java.awt.Color(0, 0, 0));
        jlblNota.setText("     Nota:");

        jcboEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jcboEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcboEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboEstudiante.addActionListener(this::jcboEstudianteActionPerformed);

        jcboCurso.setBackground(new java.awt.Color(255, 255, 255));
        jcboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboCurso.addActionListener(this::jcboCursoActionPerformed);

        jtxtNota.setBackground(new java.awt.Color(255, 255, 255));
        jtxtNota.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jbtnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jbtnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(this::jbtnGuardarActionPerformed);

        jbtnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLimpiar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);

        jTableCalificaciones.setBackground(new java.awt.Color(204, 204, 204));
        jTableCalificaciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Estudiante", "Curso", "Nota", "Observación", "Estado"
            }
        ));
        jTableCalificaciones.setGridColor(new java.awt.Color(204, 204, 204));
        jTableCalificaciones.setName(""); // NOI18N
        jTableCalificaciones.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTableCalificaciones);

        jLabelTituloSecundario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTituloSecundario.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTituloSecundario.setText("Notas Registros  ");

        jtxtObservacion.setBackground(new java.awt.Color(255, 255, 255));
        jtxtObservacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtObservacion.setForeground(new java.awt.Color(0, 0, 0));
        jtxtObservacion.setName(""); // NOI18N

        jlblObservación.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblObservación.setForeground(new java.awt.Color(0, 0, 0));
        jlblObservación.setText("Observación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblEstudiante)
                                    .addComponent(jlblNota))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlblObservación)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcboEstudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jlblCurso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTituloSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCurso)
                    .addComponent(jcboEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEstudiante)
                    .addComponent(jcboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNota)
                    .addComponent(jtxtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblObservación)
                    .addComponent(jtxtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabelTituloSecundario)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcboEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboEstudianteActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        jtxtNota.setText("");
        jtxtObservacion.setText("");

        jcboEstudiante.setSelectedIndex(0);
        jcboCurso.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        try {

            if (jtxtNota.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe ingresar una nota");
                return;
            }

            double nota;

            try {

                nota = Double.parseDouble(
                        jtxtNota.getText());

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "La nota debe ser numérica");

                return;
            }

            if (nota < 0 || nota > 100) {

                JOptionPane.showMessageDialog(
                        this,
                        "La nota debe estar entre 0 y 100");

                return;
            }

            String observacion =
                    jtxtObservacion.getText();

            Calificacion c =
                    new Calificacion();

            c.setNota(nota);

            negocio.agregar(c);
           

            JOptionPane.showMessageDialog(
                    this,
                    "Nota guardada correctamente");
            
            cargarTabla();
            
            jtxtNota.setText("");
            jtxtObservacion.setText("");
            

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage());
        } 
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jcboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCursoActionPerformed
        
    }//GEN-LAST:event_jcboCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTituloSecundario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCalificaciones;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JComboBox<String> jcboCurso;
    private javax.swing.JComboBox<String> jcboEstudiante;
    private javax.swing.JLabel jlblCurso;
    private javax.swing.JLabel jlblEstudiante;
    private javax.swing.JLabel jlblNota;
    private javax.swing.JLabel jlblObservación;
    private javax.swing.JTextField jtxtNota;
    private javax.swing.JTextField jtxtObservacion;
    // End of variables declaration//GEN-END:variables

}
