/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author yarie
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        jPanelDePestañas.add(
        "Estudiantes",
        new EstudiantePanel()
        );
        
        jPanelDePestañas.addTab(
        "Matrícula",
        new MatriculaPanel()
        );
        
        jPanelDePestañas.add(
        "Cursos",
        new CursoPanel()
        );
        
        jPanelDePestañas.add(
        "Calificaciones",
        new CalificacionesPanel()
        );
        
        jPanelDePestañas.add(
        "Reporte",
        new ReportePanel()
        );
        
        
        
        setTitle("Sistema Académico");
        setSize(900,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuArchivo = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jButtonCalificaciones = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelDePestañas = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivoNuevo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jMenuItemExportar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        Gestión = new javax.swing.JMenu();
        jMenuItemEstudiantes = new javax.swing.JMenuItem();
        jMenuItemCursos = new javax.swing.JMenuItem();
        jMenuItemMatricula = new javax.swing.JMenuItem();
        jMenuItemCalificaciones = new javax.swing.JMenuItem();
        jMenureportes = new javax.swing.JMenu();
        jMenuItemEstadisticas = new javax.swing.JMenuItem();
        jMenuItemHistorial = new javax.swing.JMenuItem();
        jMenuItemPromedios = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDelSistema = new javax.swing.JMenuItem();
        jMenuItemManual = new javax.swing.JMenuItem();

        jMenuArchivo.setText("Archivo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setName("Sistema Académico - Gestión Académica"); // NOI18N
        setSize(new java.awt.Dimension(600, 600));

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        jButtonNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNuevo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/nuevo.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setFocusable(false);
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNuevo.addActionListener(this::jButtonNuevoActionPerformed);
        jToolBar1.add(jButtonNuevo);

        jButtonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setFocusable(false);
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);
        jToolBar1.add(jButtonGuardar);

        jButtonExportar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExportar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/Exportar.png"))); // NOI18N
        jButtonExportar.setText("Exportar");
        jButtonExportar.setFocusable(false);
        jButtonExportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonExportar);

        jButtonCalificaciones.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCalificaciones.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/nota.png"))); // NOI18N
        jButtonCalificaciones.setText("Calificaciones");
        jButtonCalificaciones.setFocusable(false);
        jButtonCalificaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCalificaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCalificaciones.addActionListener(this::jButtonCalificacionesActionPerformed);
        jToolBar1.add(jButtonCalificaciones);

        jButtonReportes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReportes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/analysis.png"))); // NOI18N
        jButtonReportes.setText("Reportes");
        jButtonReportes.setFocusable(false);
        jButtonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReportes.addActionListener(this::jButtonReportesActionPerformed);
        jToolBar1.add(jButtonReportes);

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/salir.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalir.addActionListener(this::jButtonSalirActionPerformed);
        jToolBar1.add(jButtonSalir);

        jPanelDePestañas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDePestañas.setForeground(new java.awt.Color(0, 0, 0));
        jPanelDePestañas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(300, 23));

        jMenuArchivoNuevo.setBackground(new java.awt.Color(204, 204, 204));
        jMenuArchivoNuevo.setForeground(new java.awt.Color(0, 0, 0));
        jMenuArchivoNuevo.setText("Archivo");

        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(this::jMenuItemNuevoActionPerformed);
        jMenuArchivoNuevo.add(jMenuItemNuevo);

        jMenuItemGuardar.setText("Guardar");
        jMenuArchivoNuevo.add(jMenuItemGuardar);

        jMenuItemCargar.setText("Cargar");
        jMenuArchivoNuevo.add(jMenuItemCargar);

        jMenuItemExportar.setText("Exportar");
        jMenuArchivoNuevo.add(jMenuItemExportar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(this::jMenuItemSalirActionPerformed);
        jMenuArchivoNuevo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivoNuevo);

        Gestión.setText("Gestión");

        jMenuItemEstudiantes.setText("Estudiantes");
        Gestión.add(jMenuItemEstudiantes);

        jMenuItemCursos.setText("Cursos");
        Gestión.add(jMenuItemCursos);

        jMenuItemMatricula.setText("Matricula");
        Gestión.add(jMenuItemMatricula);

        jMenuItemCalificaciones.setText("Calificaciones");
        Gestión.add(jMenuItemCalificaciones);

        jMenuBar1.add(Gestión);

        jMenureportes.setText("Reportes");

        jMenuItemEstadisticas.setText("Estadisticas");
        jMenureportes.add(jMenuItemEstadisticas);

        jMenuItemHistorial.setText("Historial");
        jMenureportes.add(jMenuItemHistorial);

        jMenuItemPromedios.setText("Promedios");
        jMenureportes.add(jMenuItemPromedios);

        jMenuBar1.add(jMenureportes);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDelSistema.setText("Acerca del Sistema");
        jMenuAyuda.add(jMenuItemAcercaDelSistema);

        jMenuItemManual.setText("Manual");
        jMenuAyuda.add(jMenuItemManual);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE))
                    .addComponent(jPanelDePestañas))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanelDePestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Gestión;
    private javax.swing.JButton jButtonCalificaciones;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuArchivoNuevo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAcercaDelSistema;
    private javax.swing.JMenuItem jMenuItemCalificaciones;
    private javax.swing.JMenuItem jMenuItemCargar;
    private javax.swing.JMenuItem jMenuItemCursos;
    private javax.swing.JMenuItem jMenuItemEstadisticas;
    private javax.swing.JMenuItem jMenuItemEstudiantes;
    private javax.swing.JMenuItem jMenuItemExportar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemHistorial;
    private javax.swing.JMenuItem jMenuItemManual;
    private javax.swing.JMenuItem jMenuItemMatricula;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemPromedios;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenureportes;
    private javax.swing.JTabbedPane jPanelDePestañas;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

   
}

