/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author yarie
 */
public class ReportePanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportePanel
     */
    public ReportePanel() {
        initComponents();
        
        jcboTipoArchivo1.addItem("TXT");
        jcboTipoArchivo1.addItem("CSV");
        jcboGuardaren.addItem("Proyecto");
        jcboGuardaren.addItem("Escritorio");
        jcboGuardaren.addItem("Documentos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbltitulo1 = new javax.swing.JLabel();
        jPanelGrafico1 = new javax.swing.JPanel();
        jButtonExpReporte1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jcboGuardarEn = new javax.swing.JTable();
        jPanelExportar1 = new javax.swing.JPanel();
        jlblGuardar1 = new javax.swing.JLabel();
        jlblNombreDelArchivo1 = new javax.swing.JLabel();
        jlblTipo1 = new javax.swing.JLabel();
        jcboTipoArchivo1 = new javax.swing.JComboBox<>();
        jtxtNombreArchivo1 = new javax.swing.JTextField();
        jbtnExportar1 = new javax.swing.JButton();
        jcboGuardaren = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jlbltitulo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbltitulo1.setForeground(new java.awt.Color(0, 0, 0));
        jlbltitulo1.setText("Cantidad de estudiantes por carrera");

        jPanelGrafico1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGrafico1.setName("panelGrafico"); // NOI18N

        javax.swing.GroupLayout jPanelGrafico1Layout = new javax.swing.GroupLayout(jPanelGrafico1);
        jPanelGrafico1.setLayout(jPanelGrafico1Layout);
        jPanelGrafico1Layout.setHorizontalGroup(
            jPanelGrafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        jPanelGrafico1Layout.setVerticalGroup(
            jPanelGrafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButtonExpReporte1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExpReporte1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonExpReporte1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExpReporte1.setText("Exportar Reporte");
        jButtonExpReporte1.addActionListener(this::jButtonExpReporte1ActionPerformed);

        jcboGuardarEn.setBackground(new java.awt.Color(255, 255, 255));
        jcboGuardarEn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcboGuardarEn.setForeground(new java.awt.Color(0, 0, 0));
        jcboGuardarEn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Acción"
            }
        ));
        jcboGuardarEn.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jcboGuardarEn.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(jcboGuardarEn);

        jScrollPane4.setViewportView(jScrollPane5);

        jPanelExportar1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExportar1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelExportar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlblGuardar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblGuardar1.setForeground(new java.awt.Color(0, 0, 0));
        jlblGuardar1.setText("Guardar en:");

        jlblNombreDelArchivo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblNombreDelArchivo1.setForeground(new java.awt.Color(0, 0, 0));
        jlblNombreDelArchivo1.setText("Nombre del archivo:");

        jlblTipo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTipo1.setForeground(new java.awt.Color(0, 0, 0));
        jlblTipo1.setText("Tipo:");

        jcboTipoArchivo1.setBackground(new java.awt.Color(204, 204, 204));
        jcboTipoArchivo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcboTipoArchivo1.setForeground(new java.awt.Color(0, 0, 0));
        jcboTipoArchivo1.addActionListener(this::jcboTipoArchivo1ActionPerformed);

        jtxtNombreArchivo1.setBackground(new java.awt.Color(204, 204, 204));
        jtxtNombreArchivo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtNombreArchivo1.setForeground(new java.awt.Color(0, 0, 0));

        jbtnExportar1.setBackground(new java.awt.Color(204, 204, 204));
        jbtnExportar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtnExportar1.setForeground(new java.awt.Color(0, 0, 0));
        jbtnExportar1.setText("Guardar");
        jbtnExportar1.addActionListener(this::jbtnExportar1ActionPerformed);

        jcboGuardaren.setBackground(new java.awt.Color(204, 204, 204));
        jcboGuardaren.setForeground(new java.awt.Color(0, 0, 0));
        jcboGuardaren.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { null }));

        javax.swing.GroupLayout jPanelExportar1Layout = new javax.swing.GroupLayout(jPanelExportar1);
        jPanelExportar1.setLayout(jPanelExportar1Layout);
        jPanelExportar1Layout.setHorizontalGroup(
            jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExportar1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblGuardar1)
                    .addComponent(jlblNombreDelArchivo1)
                    .addComponent(jlblTipo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtNombreArchivo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtnExportar1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcboTipoArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcboGuardaren, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelExportar1Layout.setVerticalGroup(
            jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExportar1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblGuardar1)
                    .addComponent(jcboGuardaren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombreDelArchivo1)
                    .addComponent(jtxtNombreArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelExportar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTipo1)
                    .addComponent(jcboTipoArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jbtnExportar1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonExpReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jlbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(988, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanelExportar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbltitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelExportar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGrafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExpReporte1)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExpReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpReporte1ActionPerformed
         JFileChooser guardar = new JFileChooser();

        int opcion = guardar.showSaveDialog(this);


        if(opcion == JFileChooser.APPROVE_OPTION){

            try{

                FileWriter archivo = new FileWriter(
                    guardar.getSelectedFile()+".txt"
                );


                archivo.write(
                    "Reporte de estudiantes\n"
                    + "Carrera: Sistemas\n"
                    + "Cantidad: 10\n"
                );


                archivo.close();


                JOptionPane.showMessageDialog(
                    this,
                    "Archivo guardado correctamente"
                );


            }catch(Exception e){

                JOptionPane.showMessageDialog(
                    this,
                    "Error al guardar"
                );

            }
        
        }
    }//GEN-LAST:event_jButtonExpReporte1ActionPerformed

    private void jcboTipoArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboTipoArchivo1ActionPerformed

    }//GEN-LAST:event_jcboTipoArchivo1ActionPerformed

    private void jbtnExportar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExportar1ActionPerformed
                            
        JFileChooser guardar = new JFileChooser();
        
        String ubicacion = 
        jcboGuardaren.getSelectedItem().toString();

        int opcion = guardar.showSaveDialog(this);

        if(opcion == JFileChooser.APPROVE_OPTION){

            try{

                String tipo = 
                jcboTipoArchivo1.getSelectedItem().toString();

                String nombreArchivo =
                guardar.getSelectedFile().getAbsolutePath();

                if(tipo.equals("TXT")){

                    FileWriter archivo =
                    new FileWriter(nombreArchivo + ".txt");

                    archivo.write(
                    "Reporte de estudiantes\n"
                    +"Cantidad por carrera\n"
                    );

                    archivo.close();

                }else{
                    
                
                    FileWriter archivo =
                    new FileWriter(nombreArchivo + ".csv");

                    archivo.write(
                    "Carrera,Cantidad\n"
                    +"Sistemas,10\n"
                    );

                    archivo.close();
                }

                JOptionPane.showMessageDialog(
                this,
                "Archivo guardado correctamente"
                );

            }catch(Exception e){
                
                JOptionPane.showMessageDialog(
                this,
                "Error al guardar archivo"
                );
            }
        }

    }//GEN-LAST:event_jbtnExportar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExpReporte1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExportar1;
    private javax.swing.JPanel jPanelGrafico1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbtnExportar1;
    private javax.swing.JTable jcboGuardarEn;
    private javax.swing.JComboBox<String> jcboGuardaren;
    private javax.swing.JComboBox<String> jcboTipoArchivo1;
    private javax.swing.JLabel jlblGuardar1;
    private javax.swing.JLabel jlblNombreDelArchivo1;
    private javax.swing.JLabel jlblTipo1;
    private javax.swing.JLabel jlbltitulo1;
    private javax.swing.JTextField jtxtNombreArchivo1;
    // End of variables declaration//GEN-END:variables
   
}
